name: Fatih-Garantili-Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Theos and SDK
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "THEOS=~/theos" >> $GITHUB_ENV
          
          mkdir -p ~/theos/sdks
          curl -L https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz | tar -xJ -C ~/theos/sdks
          
          echo "~/theos/bin" >> $GITHUB_PATH

      - name: Build Tweak
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1 DEBUG=0
          
      - name: Upload Dylib
        uses: actions/upload-artifact@v4
        with:
          name: Fatih-Hile-Dosyasi
          path: .theos/obj/debug/*.dylib
